<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="/css/styles.css" rel="stylesheet" type="text/css" />

  <title>Document</title>
</head>
<body>
  <div class="app"></div>
<script type="text/javascript" src="/node_modules/steal/steal.js"></script>
</body>
</html>
